Add extension for skipping sad songs
3raxton/spicetify-custom-apps pull request #2
Opened 2021-01-18 02:49 UTC by JakeRoggenbuck

2021-01-18 21:33 UTC, 3raxton requested changes
Hey @JakeRoggenbuck, thanks for the PR; it helped me make the repo a bit more organized for future contributors and users of Spicetify searching for custom apps. 

That being said, these changes require a few things from you. Would you please place your custom app in a folder along with a README file detailing what it does and at least one screenshot of what it looks like when working? You can find more details on the structure [here.](https://github.com/3raxton/spicetify-custom-apps/blob/main/CONTRIBUTING.md#contributing-your-custom-apps-to-this-repo-follow-the-instructions-below)

Additionally, If you'd also like to add your name, a link to your repo, website, etc., and a link to your custom app repo, you can do so in the [AUTHORS.md file](https://github.com/3raxton/spicetify-custom-apps/blob/main/AUTHORS.md). It's not required, but I figured it might be nice to share attributions to custom app authors. 

Thanks for helping kickstart this project. I'm glad to have you as part of the repo! Let me know if you have any questions.

2021-01-20 03:42 UTC, JakeRoggenbuck commented
@3raxton Yeah, sure thing! I added the stuff in listed in the CONTRIBUTING.md. Thanks so much!

2021-01-20 05:13 UTC, 3raxton commented
This looks good! There may be a problem with the picture, but I can't be sure until I merge. I'll keep you updated. Also, to confirm, you don't want to add anything to AUTHORS.md?

2021-01-20 05:44 UTC, JakeRoggenbuck commented
Thanks! I added my extension and name to the AUTHORS.md.

2021-01-20 06:08 UTC, 3raxton commented on AUTHORS.md
> +
Would you mind removing this line?

2021-01-20 06:09 UTC, 3raxton commented on AUTHORS.md
> +
Edited for claity

2021-01-20 06:33 UTC, 3raxton commented
All is looking good! Thanks for keeping this in line with the current files' look; I appreciate it as tedious as it may have been. Glad to have you as part of the repo; this PR is merged!

2021-01-20 06:34 UTC, merged

2021-01-20 06:36 UTC, JakeRoggenbuck commented
Yay! Thank you!

2021-01-20 06:42 UTC, 3raxton commented
One thing to note here, the screenshot is not hosted correctly. I believe the adequate approach is hosting it in your forked repo and then committing it as another PR. Would you mind doing that?

2021-01-20 15:46 UTC, 3raxton commented
@JakeRoggenbuck

2021-01-21 01:13 UTC, JakeRoggenbuck commented
Sure, I can do that!

2021-01-21 01:20 UTC, JakeRoggenbuck commented
Done in #6

2021-01-21 03:40 UTC, 3raxton commented
Good stuff, appreciate the fast response!